### ISSUE TITLE
non-snapshot version

### ISSUE THREAD

**Issue by mbuczko** [tuhlmann/permissions#1]
thanks a lot for such a useful library. would you consider releasing non-snapshot version?

**Comment by tuhlmann** [comment]
@mbuczko I'm so sorry for not responding, I just now saw the issue in github.

I will release a non snapshot version after finalising the API.

One question: do you use the "Bitmask Permissions" part or is this rather a distraction for you.

Kind Regards,
Torsten.

**Comment by mbuczko** [comment]
hey Torsten, thanks for response. I'm happy to hear that you didn't drop off this project yet :)

regarding your question, I haven't used bitmask permissions so far but honestly I don't consider them as a distraction. I think I will have a chance to use them soon.

best,
michał

**Comment by iku000888** [comment]
Just another voice in favor of a non snapshot version so I could use this for work ;)

**Comment by tuhlmann** [comment]
@iku000888 I apologize. I had to move away from Clojure and can't currently support this library. Please feel free to take over development and publish a version that fits your needs.

Torsten.

**Comment by iku000888** [comment]
Absolutely no need to apologize! Sorry if I made you feel pressured.
Stuff happens in life so I hope it brings you back to clojure sometime :)
Anyways thank you for the great work! Will see how I can consume this lib at work :pray:
